## Numpy

In [1]:
import numpy as np

### np.array

In [2]:
# create a nd-array of 2X2
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
type(a) # to check the type

numpy.ndarray

In [4]:
a.shape  #returns the tuple of row and col

(2, 2)

In [5]:
a.size  # give count of elements in array

4

In [6]:
a.dtype  # datatype array elements

dtype('int32')

In [7]:
a.ndim  # no. of dimensions

2

### Make arrays with constant values

In [13]:
#np.zeros((row,col))
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#np.ones((row,col))
a=np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#np.full((row,col),values)
a=np.full((3,3),77)
a

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

### Random value matrixs 

In [18]:
a=np.random.random((3,3))
a
#0->1

array([[0.70409638, 0.45837665, 0.16716093],
       [0.97720585, 0.34319917, 0.68555489],
       [0.41241662, 0.77950441, 0.95910846]])

In [19]:
#np.random.randint(low,high,shape)
a=np.random.randint(0,50,(3,5))
a

array([[28, 25, 49, 31,  9],
       [49, 45, 40, 35,  7],
       [31, 10,  6, 35, 28]])

### nd-array with series data

In [20]:
#arange(low,high,step)
a=np.arange(0,50,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
#np.linspace(low,high, no of values)
a=np.linspace(0,30,10)
a

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

## Reshape

In [26]:
a.shape

(10,)

In [29]:
a=a.reshape((5,2))
a

array([[ 0.        ,  3.33333333],
       [ 6.66666667, 10.        ],
       [13.33333333, 16.66666667],
       [20.        , 23.33333333],
       [26.66666667, 30.        ]])

In [34]:
b=a.reshape((1,-1)) # one row multiple columns
b

array([[ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
        16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ]])

In [33]:
b=a.reshape((-1,1)) # multiple rows and one column
b

array([[ 0.        ],
       [ 3.33333333],
       [ 6.66666667],
       [10.        ],
       [13.33333333],
       [16.66666667],
       [20.        ],
       [23.33333333],
       [26.66666667],
       [30.        ]])

### Access Elements from ndarray

In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a[0][0]

1

In [39]:
#slicing
a[1:2,1:]

array([[5, 6]])